# Generated by Django 5.1.6 on 2025-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeteoDatas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=20)),
                ("longitude", models.CharField(max_length=20)),
                ("region", models.CharField(max_length=50)),
                ("elevation", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.IntegerField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "temperature_max",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "temperature_min",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "temperature_trend_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "temperature_trend_3hours",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "temperature_trend_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("pressure", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pressure_trend_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pressure_trend_3hours",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pressure_trend_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "humidity_trend_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "humidity_trend_3hours",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "humidity_trend_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precipitation", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precipitation_trend_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precipitation_trend_3hours",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precipitation_trend_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=10)),
                ("wind_direction", models.CharField(max_length=20)),
                ("wind_gust", models.DecimalField(decimal_places=2, max_digits=10)),
                ("wind_gust_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("wind_gust_max_dir", models.CharField(max_length=20)),
                ("wind_chill", models.DecimalField(decimal_places=2, max_digits=10)),
                ("uv_index", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
