# Generated by Django 5.1.6 on 2025-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ScrapedData", "0002_remove_meteodatas_elevation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meteodatas",
            name="id",
        ),
        migrations.AlterField(
            model_name="meteodatas",
            name="region",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
