# Generated by Django 5.1.6 on 2025-03-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ScrapedData", "0003_remove_meteodatas_id_alter_meteodatas_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meteodatas",
            name="date",
        ),
        migrations.RemoveField(
            model_name="meteodatas",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="meteodatas",
            name="precipitation",
        ),
        migrations.RemoveField(
            model_name="meteodatas",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="meteodatas",
            name="time",
        ),
        migrations.RemoveField(
            model_name="meteodatas",
            name="wind_direction",
        ),
        migrations.RemoveField(
            model_name="meteodatas",
            name="wind_speed",
        ),
    ]
