from django.db import models

# Create your models here.

class MeteoDatas(models.Model):
    station = models.CharField(max_length=100)
    latitude = models.CharField(max_length=20)
    longitude = models.CharField(max_length=20)
    region = models.CharField(max_length=50)
    elevation = models.IntegerField()
    date = models.DateField()
    time = models.IntegerField()
    temperature = models.DecimalField(max_digits=10, decimal_places=2)
    temperature_max = models.DecimalField(max_digits=10, decimal_places=2)
    temperature_min = models.DecimalField(max_digits=10, decimal_places=2)
    temperature_trend_hour = models.DecimalField(max_digits=10, decimal_places=2)
    temperature_trend_3hours = models.DecimalField(max_digits=10, decimal_places=2)
    temperature_trend_day = models.DecimalField(max_digits=10, decimal_places=2)
    pressure = models.DecimalField(max_digits=10, decimal_places=2)
    pressure_trend_hour = models.DecimalField(max_digits=10, decimal_places=2)
    pressure_trend_3hours = models.DecimalField(max_digits=10, decimal_places=2)
    pressure_trend_day = models.DecimalField(max_digits=10, decimal_places=2)
    humidity = models.DecimalField(max_digits=10, decimal_places=2)
    humidity_trend_hour = models.DecimalField(max_digits=10, decimal_places=2)
    humidity_trend_3hours = models.DecimalField(max_digits=10, decimal_places=2)
    humidity_trend_day = models.DecimalField(max_digits=10, decimal_places=2)
    precipitation = models.DecimalField(max_digits=10, decimal_places=2)
    precipitation_trend_hour = models.DecimalField(max_digits=10, decimal_places=2)
    precipitation_trend_3hours = models.DecimalField(max_digits=10, decimal_places=2)
    precipitation_trend_day = models.DecimalField(max_digits=10, decimal_places=2)
    wind_speed = models.DecimalField(max_digits=10, decimal_places=2)
    wind_direction = models.CharField(max_length=20)
    wind_gust = models.DecimalField(max_digits=10, decimal_places=2)
    wind_gust_max = models.DecimalField(max_digits=10, decimal_places=2)
    wind_gust_max_dir = models.CharField(max_length=20)
    wind_chill = models.DecimalField(max_digits=10, decimal_places=2)
    uv_index = models.DecimalField(max_digits=10, decimal_places=2)
